# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 17:26
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('applicants_name_bangla', models.CharField(blank=True, max_length=255, null=True)),
                ('applicants_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fathers_name_bangla', models.CharField(blank=True, max_length=255, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name_bangla', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('spouses_name_bangla', models.CharField(blank=True, max_length=255, null=True)),
                ('spouses_name', models.CharField(blank=True, max_length=255, null=True)),
                ('other_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=11, null=True)),
                ('present_address', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('national_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('nominees_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nominess_relationship_with_applicant', models.CharField(blank=True, max_length=255, null=True)),
                ('nominees_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_booking', models.DateField(blank=True, null=True)),
                ('regular_price', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('rate_per_katha', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('total_price_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_money', models.IntegerField(blank=True, null=True)),
                ('down_payment', models.IntegerField(blank=True, null=True)),
                ('total_payment', models.IntegerField(blank=True, null=True)),
                ('total_payment_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('rest_amount', models.IntegerField(blank=True, null=True)),
                ('rest_amount_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_of_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('one_time', models.IntegerField(blank=True, null=True)),
                ('installment', models.IntegerField(blank=True, null=True)),
                ('no_of_installment', models.IntegerField(blank=True, null=True)),
                ('per_installment', models.IntegerField(blank=True, null=True)),
                ('in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='plots.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.CharField(blank=True, max_length=255, null=True)),
                ('road_no', models.CharField(blank=True, max_length=255, null=True)),
                ('sector_block', models.CharField(blank=True, max_length=255, null=True)),
                ('plot_size', models.CharField(blank=True, max_length=255, null=True)),
                ('facing', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_plot', models.CharField(blank=True, max_length=255, null=True)),
                ('total_land', models.CharField(blank=True, max_length=255, null=True)),
                ('total_land_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot', to='plots.Booking')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together=set([('plot_no', 'road_no', 'sector_block')]),
        ),
    ]
